project:
  type: website
  output-dir: docs

website:
  title: "Paneles Flora UAM"
  favicon: materials/bot_icon.png
  sidebar:
    background: primary
    logo: "leaf.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/HerbarioDocenteUAM/Paneles
        text: GitHub Herbario Docente UAM
    style: docked
    contents:
      - href: index.qmd
        text: Inicio
      - href: paneles.qmd
        text: Paneles
      - href: https://www.uam.es/Ciencias/Botánica/1446766816493.htm?language=es
        text: Página de la unidad de Botánica



format:
  html:
    theme: spacelab
    # css: styles.css
    toc: true

execute:
  freeze: auto

